# Generated by Django 4.0.3 on 2022-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.TextField(default='description'),
        ),
    ]
