# Generated by Django 4.0.3 on 2022-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_remove_author_age_author_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='jenre',
            name='jenre_type',
            field=models.CharField(max_length=80),
        ),
    ]
