# Generated by Django 4.0.3 on 2022-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_description',
            field=models.TextField(),
        ),
    ]
